name: Terraform Feature Branch CI

on:
  push:
    branches:
      - 'feature/**'

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Azure_Landing_zone

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Terraform Init
      - name: Terraform Init
        run: terraform init -input=false

      # 4. Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 5. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 6. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false -no-color