name: Terraform Feature Branch CI

on:
  push:
    branches:
      - "feature/**"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Azure_Landing_zone

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init -input=false

      # 5. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 6. Login to Azure using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      # 8. Upload Terraform Plan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: Azure_Landing_zone/tfplan