name: Terraform Plan

on:
  push:
    branches:
      - 'feature/**'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      # 1. Get code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Initialize Terraform
      - name: Terraform Init
        run: terraform init
       - name: Debug Terraform Files
      - run: |
         pwd
         ls -la
         find . -name "*.tf" -type f
         terraform version
         terraform fmt -check -recursive

      # 4. Check Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 5. Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # 6. Generate Terraform Plan
      - name: Terraform Plan
        run: terraform plan